singleQuote: true
trailingComma: es5
overrides:
  - files: ["*.yaml", "*.yml"]
    options:
      singleQuote: false
  - files: ["*.ts", "*.tsx"]
    options:
      arrowParens: avoid # backward compatible with 1.19, 2.0 new default "always"
      parser: typescript
  - files: ["*.js", "*.cjs", "*.mjs"]
    options:
      arrowParens: avoid # backward compatible with 1.19, 2.0 new default "always"
  - files: ["*.svg"]
    options:
      parser: html
plugins:
  - prettier-plugin-organize-imports
